env = "local"
app_name = "GO Web Scoket"
debug = "on"
storage_path = "/data/app/"
address = ":3000"
static_url = "public/"
login_time = 2
default_page_size = 10

[database]
[database.default]
enable = true
driver = "mysql"
dsn = ""
max_open_conns = 10
max_idle_conns = 5
show_sql = false

[redis]
[redis.default]
addr = ""
password = ""
db = 0
