// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"net/http"
	"websocket/api/handler"
	"websocket/api/handler/api"
	"websocket/api/handler/push"
	"websocket/api/handler/user"
	"websocket/api/middleware"
	"websocket/api/router"
	"websocket/cache"
	"websocket/config"
	"websocket/connection"
	"websocket/repo"
)

// Injectors from wire.go:

func Initialize() *http.Server {
	redis := connection.NewRedis()
	userCache := cache.NewUserCache(redis)
	mySQl := connection.NewMySQL()
	app := repo.NewApp(mySQl)
	middleWare := middleware.NewMiddleWare(userCache, app)
	repoUser := repo.NewUser(mySQl)
	apiApi := api.NewApi(userCache, repoUser)
	message := repo.NewMessage(mySQl)
	messageRead := repo.NewMessageRead(mySQl)
	pushPush := push.NewPush(message, messageRead)
	userUser := user.NewUser()
	ws := handler.NewWs(app)
	handlerHandler := &handler.Handler{
		Api:  apiApi,
		Push: pushPush,
		User: userUser,
		Ws:   ws,
	}
	routerRouter := router.NewRouter(middleWare, handlerHandler)
	server := NewHttp(routerRouter)
	return server
}

// wire.go:

func NewHttp(router2 *router.Router) *http.Server {
	return &http.Server{
		Addr:           config.App.Address,
		Handler:        router2.Run(),
		MaxHeaderBytes: 1 << 20,
	}
}

var providerSet = wire.NewSet(connection.NewMySQL, connection.NewRedis, cache.NewUserCache, repo.NewApp, repo.NewMessage, repo.NewUser, repo.NewMessageRead, api.NewApi, push.NewPush, user.NewUser, handler.NewWs, middleware.NewMiddleWare, router.NewRouter, wire.Struct(new(handler.Handler), "*"), NewHttp)
